default_install_hook_types: [pre-commit, pre-push]

repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: uv run --locked black
      language: system
      types_or: [python, pyi, jupyter]
      require_serial: true
      stages: [pre-commit]

    - id: ruff-check
      name: ruff check
      entry: uv run --locked ruff check
      language: system
      types_or: [python, pyi, jupyter]
      stages: [pre-commit]
      args: [
        "--output-format=grouped",
      ]

    - id: pytest-coverage
      name: pytest with coverage
      entry: uv run --locked coverage run -m pytest
      language: system
      pass_filenames: false
      always_run: true
      stages: [pre-push]

    - id: coverage-report
      name: coverage report
      entry: uv run --locked coverage report --fail-under=90
      language: system
      pass_filenames: false
      always_run: true
      stages: [pre-push]
      verbose: true
      
    - id: mypy
      name: mypy
      entry: uv run --locked mypy
      language: system
      pass_filenames: false
      always_run: true
      stages: [pre-push]
