name: Deploy to TestPyPI

on: workflow_dispatch

jobs:
  build:
    name: Build and validate distribution
    uses: ./.github/workflows/build.yaml

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/fluopy/
    permissions:
      id-token: write

    steps:
    - name: Download validated distributions
      uses: actions/download-artifact@v8
      with:
        name: python-package-distributions
        path: dist
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
